queue:
    queuename: posp.queue1
    username: posp
    password: posp
    host: localhost
    port: 5672
socket:
    client:
      port: 8583
      host: localhost
db:
    host: localhost
    user: root
    password: root123
    database: posp
